apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbAdmin-deployment
spec:
  selector:
    matchLabels:
      app: sbAdmin
  replicas: 1
  template:
    metadata:
      labels:
        app: sbAdmin
    spec:
      imagePullSecrets:
        - name: sbAdmin-registry-key
      containers:
        - name: sbAdmin
          image: 365583262659.dkr.ecr.eu-west-3.amazonaws.com/sbAdmin-repo:latest
          ports:
            - containerPort: 9090
          env:
            - name: PROFILE
              value: prod
            - name: LOG_PATH
              value: /app/logs
            - name: LOGSTASH_HOST
              value: logstash
            - name: LOGSTASH_PORT
              value: "9999"
            - name: EUREKA_DISCOVERY
              value: http://eureka:8761
            - name: ENABLE_EUREKA
              value: "true"
            - name: ENABLE_KUBERNETES
              value: "false"
            - name: ENABLE_KUBERNETES_DISCOVERY
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: sbAdmin
spec:
  selector:
    app: sbAdmin
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 8001
