apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  selector:
    matchLabels:
      app: search
  replicas: 1
  template:
    metadata:
      labels:
        app: search
    spec:
      # imagePullSecrets:
      #   - name: search-registry-key
      containers:
        - name: search
          image: 365583262659.dkr.ecr.eu-west-3.amazonaws.com/search_repo:latest
          ports:
            - containerPort: 8002
          env:
            - name: PROFILE
              value: prod
            - name: LOG_PATH
              value: /app/logs
            - name: LOGSTASH_HOST
              value: logstash
            - name: LOGSTASH_PORT
              value: "5044"
            - name: SBADMIN_URL
              value: http://sbadmin:9090
            - name: EUREKA_DISCOVERY
              value: http://eureka:8761
            - name: ENABLE_EUREKA
              value: "true"
            - name: ENABLE_KUBERNETES
              value: "false"
            - name: ENABLE_KUBERNETES_DISCOVERY
              value: "false"
            - name: KEYCLOAK
              value: http://keycloak:8180
            - name: REALM_NAME
              value: add
            - name: REALM_CLIENT
              value: addClient
            - name: KEYCLOAK_SECRET
              value: 8ya7tuJnY74935tgbI1YwBDcejYSNfRD
            - name: ES_URL
              value: elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  selector:
    app: search
  ports:
    - name: http
      port: 8002
      protocol: TCP
      targetPort: 8002
