apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      imagePullSecrets:
        - name: eureka-registry-key
      containers:
        - name: eureka
          image: 365583262659.dkr.ecr.eu-west-3.amazonaws.com/eureka-repo:latest
          ports:
            - containerPort: 8761
          env:
            - name: PROFILE
              value: prod
            - name: LOG_PATH
              value: /app/logs
            - name: LOGSTASH_HOST
              value: logstash
            - name: LOGSTASH_PORT
              value: "9999"
            - name: SBADMIN_URL
              value: http://sbadmin:9090
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
  - name: http
    port: 8761
    protocol: TCP
    targetPort: 8761
