apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
        - name: gateway-registry-key
      containers:
        - name: gateway
          image: 365583262659.dkr.ecr.eu-west-3.amazonaws.com/gateway-repo:latest
          ports:
            - containerPort: 80
          env:
            - name: PROFILE
              value: prod
            - name: LOG_PATH
              value: /app/logs
            - name: LOGSTASH_HOST
              value: logstash
            - name: LOGSTASH_PORT
              value: "9999"
            - name: SBADMIN_URL
              value: http://sbadmin:9090
            - name: EUREKA_DISCOVERY
              value: http://eureka:8761

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
