apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  selector:
    matchLabels:
      app: notification
  replicas: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      imagePullSecrets:
        - name: notification-registry-key
      containers:
        - name: notification
          image: 365583262659.dkr.ecr.eu-west-3.amazonaws.com/notification-repo:latest
          ports:
            - containerPort: 8001
          env:
            - name: PROFILE
              value: prod
            - name: LOG_PATH
              value: /app/logs
            - name: LOGSTASH_HOST
              value: logstash
            - name: LOGSTASH_PORT
              value: "9999"
            - name: SBADMIN_URL
              value: http://sbadmin:9090
            - name: EUREKA_DISCOVERY
              value: http://eureka:8761
            - name: ENABLE_EUREKA
              value: "true"
            - name: ENABLE_KUBERNETES
              value: "false"
            - name: ENABLE_KUBERNETES_DISCOVERY
              value: "false"
            - name: MYSQL
              value: mysql:3306
            - name: DB_NAME
              value: notification
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: rootroot
            - name: KEYCLOAK
              value: http://keycloak:8180
            - name: REALM_NAME
              value: add
            - name: REALM_CLIENT
              value: addClient
            - name: KEYCLOAK_SECRET
              value: 5d7313b6-55e7-46ad-84b8-38f5e176d554
           
---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  ports:
    - name: http
      port: 8001
      protocol: TCP
      targetPort: 8001
